bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),

]

images/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
    '''
    для хранения изображений на платформе
    '''
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            blank=True)
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

    class Meta:
        indexes = [models.Index(fields=['-created']), ]
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        '''
        переопределbk метод save() модели Image, чтобы автоматически
        генерировать поля slug на основе значения поля title
        '''
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

images/forms.py
import requests
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify

from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'url', 'description']
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        '''
        переопределил метод save() формы, чтобы получать файл изображения по
        переданному URL-адресу и сохранить его в файловой системе.
        '''
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'
        response = requests.get(image_url)
        image.image.save(image_name, ContentFile(response.content), save=False)
        if commit:
            image.save()
        return image

images/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST

from .forms import ImageCreateForm
from .models import Image


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    return render(request,
                  'images/image/detail.html',
                  {'section': 'images',
                   'image': image})


@login_required  # предотвращает доступ неаутентифицированных пользователей
def image_create(request):
    '''
    представление хранения изображений на сайте
    '''
    if request.method == 'POST':
        # форма отправлена
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # данные в форме валидны
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            # назначить текущего пользователя элементу
            new_image.user = request.user
            new_image.save()
            messages.success(request, 'Image added successfully')
            # перенаправить к представлению детальной информации о только что созданном элементе
            return redirect(new_image.get_absolute_url())
    else:
        # скомпоновать форму с данными, предоставленными букмарклетом методом GET
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/image/create.html', {'section': 'images', 'form': form})


@login_required  # предотвращает доступ неаутентифицированных пользователей
@require_POST  # возвращает объект HttpResponseNotAl lowed (код состояния, равный 405), в случае если HTTP-запрос выполнен не методом POST.
def image_like(request):
    image_id = request.POST.get('id')  # ИД объекта изображения, над которым пользователь выполняет действие
    action = request.POST.get('action')  # действие, которое пользователь хочет выполнить. like либо unlike.
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})

images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}
Bookmark an image
{% endblock %}

{% block content %}
<h1>Bookmark an image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form method="post">{{ form.as_p }} {% csrf_token %}<input type="submit" value="Bookmark it!">
</form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}
{{ image.title }}
{% endblock %}

{% block content %}
<h1>{{ image.title }}</h1>

{% load thumbnail %}
<a href="{{ image.image.url }}">
    <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
</a>

{% with total_likes=image.users_like.count users_like=image.users_like.all %}
<div class="image-info">
    <div>
        <span class="count">
            <span class="total">{{ total_likes }}</span> like{{ total_likes|pluralize }}
        </span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
            {% if request.user not in users_like %}
            Like
            {% else %}
            Unlike
            {% endif %}
        </a>
    </div>
    {{ image.description|linebreaks }}
</div>
<div class="image-likes">
    {% for user in image.users_like.all %}
    <div>
        {% if user.profile.photo %}
        <img src="{{ user.profile.photo.url }}">
        {% endif %}
        <p>{{ user.first_name }}</p>
    </div>
    {% empty %}
    Nobody likes this image yet.
    {% endfor %}
</div>
{% endwith %}
{% endblock %}

{% block domready %}
const url = '{% url "images:like" %}';
const csrftoken = Cookies.get('csrftoken'); // Убедитесь, что вы используете js-cookie правильно

var options = {
  method: 'POST',
  headers: {'X-CSRFToken': csrftoken},
  credentials: 'include', // Убедитесь, что cookies отправляются с запросом
  mode: 'same-origin'
};

document.querySelector('a.like').addEventListener('click', function(e){
  e.preventDefault();
  var likeButton = this;
  var formData = new FormData();
  formData.append('id', likeButton.dataset.id);
  formData.append('action', likeButton.dataset.action);
  options['body'] = formData;

  fetch(url, options)
    .then(response => {
      if (!response.ok) {
        throw new Error('Network response was not ok ' + response.statusText);
      }
      return response.json();
    })
    .then(data => {
      if (data['status'] === 'ok') {
        var previousAction = likeButton.dataset.action;
        var action = previousAction === 'like' ? 'unlike' : 'like';
        likeButton.dataset.action = action;
        likeButton.textContent = action.charAt(0).toUpperCase() + action.slice(1); // Capitalize first letter

        var likeCount = document.querySelector('span.count .total');
        var totalLikes = parseInt(likeCount.textContent, 10);
        likeCount.textContent = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1; // Исправьте на минус
      }
    })
    .catch(error => {
      console.error('Fetch Error:', error);
    });
});
{% endblock %}